# Generated by Django 4.2.7 on 2023-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_created_transaction_fee_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(blank=True, default='f1393b116a', editable=False, max_length=10, unique=True),
        ),
    ]
