# Generated by Django 4.2.7 on 2023-12-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(blank=True, default='07d8edc4dc', editable=False, max_length=10, unique=True),
        ),
    ]
