# Generated by Django 4.2.7 on 2024-01-04 12:15

from django.db import migrations, models
import transactions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_category_alter_transaction_reference_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='url',
            new_name='shareable_url',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(blank=True, default=transactions.utils.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
    ]
